import type { AccentPattern } from "./types";

/**
 * 강조 디바이스 35종. 슬라이드 안에 박히는 작은 시그니처 컴포넌트.
 * Stage 1에서 0~1개 선택, Stage 2가 슬라이드 합성 시 끼워넣음.
 */

export const ACCENTS: AccentPattern[] = [
  {
    id: "ac-dark-insight-box",
    category: "accent",
    name: "Dark Insight Box",
    purpose: "검정 배경 + 흰 텍스트로 핵심 메시지 분리",
    inputSignature: "1~2 sentences of high-density insight",
    placement: "inline",
    visualSketch: "█████████████\n█  INSIGHT  █\n█  white    █\n█████████████",
    tokenHints: ["colors.background", "colors.textInverse", "borderRadius.md"],
  },
  {
    id: "ac-brand-product-card-32",
    category: "accent",
    name: "Brand Color Product Card (radius 32)",
    purpose: "강조 1개 카드 — brand color, 우상/좌상 atmospheric blur",
    inputSignature: "headline + 1 line + (optional) icon",
    placement: "inline",
    visualSketch: "╭───────────╮\n│ ◯       ◯ │\n│ Headline   │\n│ subhead   │\n╰───────────╯",
    tokenHints: ["colors.brandPrimary", "borderRadius.lg"],
  },
  {
    id: "ac-hairline-divider",
    category: "accent",
    name: "Hairline Divider",
    purpose: "섹션 간 시각적 호흡 — 1px hairline + 여백",
    inputSignature: "between two content blocks",
    placement: "strip",
    visualSketch: "...content above\n──────────────\n...content below",
    tokenHints: ["colors.hairline", "spacing.sectionGap"],
  },
  {
    id: "ac-vertical-rule",
    category: "accent",
    name: "Vertical Rule",
    purpose: "2컬럼 사이 세로 hairline",
    inputSignature: "between two side-by-side columns",
    placement: "strip",
    visualSketch: "col 1 │ col 2",
    tokenHints: ["colors.hairline"],
  },
  {
    id: "ac-eyebrow-caption",
    category: "accent",
    name: "Eyebrow Caption",
    purpose: "헤더 상단 작은 라벨 (제N장 · 소주제)",
    inputSignature: "small categorical label",
    placement: "corner",
    visualSketch: "PART · TWO ──────",
    tokenHints: ["typography.caption", "colors.textMuted"],
  },
  {
    id: "ac-pill-tab",
    category: "accent",
    name: "Pill Tab Badge",
    purpose: "pill 모양 작은 뱃지 (NEW, BETA, +)",
    inputSignature: "1~2 word label",
    placement: "inline",
    visualSketch: "( NEW )",
    tokenHints: ["borderRadius.pill", "colors.brandPrimary"],
  },
  {
    id: "ac-coral-strip",
    category: "accent",
    name: "Brand Color Strip",
    purpose: "슬라이드 좌단 또는 상단의 가는 brand color 띠",
    inputSignature: "background context layer",
    placement: "strip",
    visualSketch: "▓│ content area",
    tokenHints: ["colors.brandPrimary"],
  },
  {
    id: "ac-atmospheric-blur-corner",
    category: "accent",
    name: "Atmospheric Blur (corner)",
    purpose: "카드 모서리의 부드러운 흰 원형 블러 — 깊이 추가",
    inputSignature: "decorative only",
    placement: "corner",
    visualSketch: "◯       ◯\n  content  \n◯       ◯",
    tokenHints: ["colors.brandPrimary"],
  },
  {
    id: "ac-large-quote-mark",
    category: "accent",
    name: "Oversized Quote Mark",
    purpose: '큰 " 마크를 background처럼 깔기',
    inputSignature: "quote content",
    placement: "background",
    visualSketch: '\"\"\n   quote here\n   — Author',
    tokenHints: ["typography.hero", "colors.hairline"],
  },
  {
    id: "ac-stat-stack-vertical",
    category: "accent",
    name: "Stat Stack (vertical)",
    purpose: "여러 stat을 세로 스택 — 우측 사이드바",
    inputSignature: "3 numbers with label",
    placement: "inline",
    visualSketch: "87%\nusers\n─\n4.2B\nmarket\n─\n3.4×\ngrowth",
    tokenHints: ["typography.stat", "colors.hairline"],
  },
  {
    id: "ac-icon-grid-9",
    category: "accent",
    name: "Icon Grid (3×3 deco)",
    purpose: "9개 작은 아이콘 그리드 — 카테고리 아이콘 모음",
    inputSignature: "decorative or feature icon set",
    placement: "inline",
    visualSketch: "◆ ◇ ◆\n◇ ◆ ◇\n◆ ◇ ◆",
    tokenHints: ["colors.textMuted", "spacing.itemGap"],
  },
  {
    id: "ac-page-number-corner",
    category: "accent",
    name: "Page Number (NN format)",
    purpose: "우하단 작은 페이지 번호 '01' 형식 (슬래시 없음)",
    inputSignature: "slide index",
    placement: "corner",
    visualSketch: "                01",
    tokenHints: ["typography.caption", "colors.textMuted"],
  },
  {
    id: "ac-logo-bottom-left",
    category: "accent",
    name: "Brand Logo (bottom-left)",
    purpose: "좌하단 회사 로고 — 모든 슬라이드 일관",
    inputSignature: "decorative",
    placement: "corner",
    visualSketch: "[logo]",
    tokenHints: ["spacing.slideMarginX"],
  },
  {
    id: "ac-arrow-callout",
    category: "accent",
    name: "Arrow Callout",
    purpose: "차트의 특정 포인트를 → 화살표 + 라벨로 지시",
    inputSignature: "specific data point + comment",
    placement: "inline",
    visualSketch: "    ●\n    │\n    └─→ note",
    tokenHints: ["colors.text"],
  },
  {
    id: "ac-highlight-circle",
    category: "accent",
    name: "Highlight Circle",
    purpose: "단어/숫자 주위에 손그림 같은 원형 표시",
    inputSignature: "word or number to circle",
    placement: "inline",
    visualSketch: "value (○87%○)",
    tokenHints: ["colors.brandPrimary"],
  },
  {
    id: "ac-numbered-bullet-big",
    category: "accent",
    name: "Numbered Bullet (big)",
    purpose: "01·02·03 big number markers — 카운트 강조",
    inputSignature: "ordered list items",
    placement: "inline",
    visualSketch: "[01]  [02]  [03]",
    tokenHints: ["typography.display", "colors.brandPrimary"],
  },
  {
    id: "ac-progress-dot-row",
    category: "accent",
    name: "Progress Dot Row",
    purpose: "현재 위치 표시 dot row (carousel indicator처럼)",
    inputSignature: "total + current index",
    placement: "corner",
    visualSketch: "● ● ● ◯ ◯",
    tokenHints: ["colors.brandPrimary", "colors.hairline"],
  },
  {
    id: "ac-stat-arrow-delta",
    category: "accent",
    name: "Stat with Arrow Delta",
    purpose: "stat 옆에 ↑+12% / ↓-5% 같은 변화량 표시",
    inputSignature: "value + delta sign + delta value",
    placement: "inline",
    visualSketch: "$4.2B ↑ +12%",
    tokenHints: ["colors.semantic"],
  },
  {
    id: "ac-keyword-underline",
    category: "accent",
    name: "Keyword Underline",
    purpose: "본문 중 키워드만 brand color underline",
    inputSignature: "running text + words to emphasize",
    placement: "inline",
    visualSketch: "this is the ___key___ point",
    tokenHints: ["colors.brandPrimary"],
  },
  {
    id: "ac-bracket-wrap",
    category: "accent",
    name: "Bracket Wrap",
    purpose: "[ ... ] 같은 큰 대괄호로 텍스트 감싸기",
    inputSignature: "thesis statement",
    placement: "inline",
    visualSketch: "[                ]\n  Main statement   \n[                ]",
    tokenHints: ["typography.display", "colors.textMuted"],
  },
  {
    id: "ac-dot-pattern-bg",
    category: "accent",
    name: "Dot Pattern Background",
    purpose: "isubtle dot grid background — 빈 공간 quietly fill",
    inputSignature: "decorative bg",
    placement: "background",
    visualSketch: ". . . . .\n. . . . .\n. . . . .",
    tokenHints: ["colors.hairline-soft", "colors.surfaceAlt"],
  },
  {
    id: "ac-diagonal-line-bg",
    category: "accent",
    name: "Diagonal Line Background",
    purpose: "대각선 패턴 (45deg)을 surface alt로 배경",
    inputSignature: "decorative bg",
    placement: "background",
    visualSketch: "╱╱╱╱╱╱╱╱\n  content  \n╱╱╱╱╱╱╱╱",
    tokenHints: ["colors.surfaceAlt"],
  },
  {
    id: "ac-quote-mark-coral",
    category: "accent",
    name: "Coral Quote Mark",
    purpose: "brand color 큰 따옴표 + 작은 인용문",
    inputSignature: "1 short quote",
    placement: "inline",
    visualSketch: "\"\nshort quote",
    tokenHints: ["colors.brandPrimary", "typography.hero"],
  },
  {
    id: "ac-vertical-progress-line",
    category: "accent",
    name: "Vertical Progress Line",
    purpose: "좌단 세로 progress line — 슬라이드 시리즈 내 위치",
    inputSignature: "current section index",
    placement: "strip",
    visualSketch: "│\n■\n│\n│",
    tokenHints: ["colors.brandPrimary", "colors.hairline"],
  },
  {
    id: "ac-section-roman",
    category: "accent",
    name: "Roman Numeral Section",
    purpose: "I·II·III 로마숫자로 섹션 표시",
    inputSignature: "section ordinal",
    placement: "corner",
    visualSketch: "III.",
    tokenHints: ["typography.display", "colors.textMuted"],
  },
  {
    id: "ac-color-block-stack",
    category: "accent",
    name: "Color Block Stack",
    purpose: "여러 brand-related 색상의 stacked rect — 색감 강조",
    inputSignature: "decorative bg or sidebar",
    placement: "background",
    visualSketch: "▓▓\n░░\n■■\n▓▓",
    tokenHints: ["colors.dataPalette"],
  },
  {
    id: "ac-tagline-bottom",
    category: "accent",
    name: "Bottom Tagline",
    purpose: "슬라이드 최하단 brand tagline 1줄",
    inputSignature: "brand tagline",
    placement: "corner",
    visualSketch: "─────────────────\n  Build the future.",
    tokenHints: ["typography.caption", "colors.textMuted"],
  },
  {
    id: "ac-stat-with-icon",
    category: "accent",
    name: "Stat with Icon",
    purpose: "stat 옆에 작은 SVG 아이콘",
    inputSignature: "1 stat + icon hint",
    placement: "inline",
    visualSketch: "◆ 87%\n  users",
    tokenHints: ["colors.brandPrimary"],
  },
  {
    id: "ac-color-swatch-row",
    category: "accent",
    name: "Color Swatch Row",
    purpose: "brand 컬러 5개 swatch — 디자인 시스템 introduction",
    inputSignature: "brand palette",
    placement: "inline",
    visualSketch: "▓ ▓ ▓ ▓ ▓",
    tokenHints: ["colors.dataPalette", "borderRadius.sm"],
  },
  {
    id: "ac-callout-tag-corner",
    category: "accent",
    name: "Callout Tag (corner ribbon)",
    purpose: "우상단 모서리 ribbon 'NEW' 등",
    inputSignature: "1 word label",
    placement: "corner",
    visualSketch: "         ╱NEW╲",
    tokenHints: ["colors.brandPrimary", "colors.textInverse"],
  },
  {
    id: "ac-step-progress-3",
    category: "accent",
    name: "Step Progress (3-step)",
    purpose: "상단 3-step indicator (현재/완료/대기)",
    inputSignature: "current step number",
    placement: "corner",
    visualSketch: "●━━━●━━━○",
    tokenHints: ["colors.brandPrimary", "colors.hairline"],
  },
  {
    id: "ac-icon-row-features",
    category: "accent",
    name: "Icon Row (Features)",
    purpose: "기능 아이콘 4~6개 가로 — 빠른 capability scan",
    inputSignature: "4~6 icon hints with 1-word label",
    placement: "inline",
    visualSketch: "◆ ◇ ▲ ■ ●\nA  B  C  D  E",
    tokenHints: ["colors.text", "typography.caption"],
  },
  {
    id: "ac-image-mask-circle",
    category: "accent",
    name: "Circular Image Mask",
    purpose: "원형 마스킹된 인물/제품 이미지 — portrait",
    inputSignature: "portrait or product image",
    placement: "inline",
    visualSketch: "    ⓞ\n  Person Name\n  Role",
    tokenHints: ["borderRadius.pill"],
  },
  {
    id: "ac-thick-underline-title",
    category: "accent",
    name: "Thick Underline on Title",
    purpose: "타이틀 밑 4px brand color 두꺼운 밑줄",
    inputSignature: "section title",
    placement: "inline",
    visualSketch: "Title\n━━━━━",
    tokenHints: ["colors.brandPrimary"],
  },
  {
    id: "ac-numbered-checklist-card",
    category: "accent",
    name: "Numbered Checklist Card",
    purpose: "01·02·03 + ✓ 카드 — multi-step done indicator",
    inputSignature: "3~5 done items with label",
    placement: "inline",
    visualSketch: "[01 ✓]\n[02 ✓]\n[03 ─]",
    tokenHints: ["colors.brandPrimary", "borderRadius.md"],
  },
];
