import type { SkeletonPattern } from "./types";

/**
 * 레이아웃 골격 35종. 슬라이드 그리드 구조를 정의.
 * AI가 콘텐츠 의도에 맞는 골격을 1개 선택 → Stage 2 합성에 reference로 사용.
 */

export const SKELETONS: SkeletonPattern[] = [
  // ── Cover variants ───────────────────────────────────────
  {
    id: "sk-cover-centered-hero",
    category: "skeleton",
    name: "Centered Hero Cover",
    purpose: "전통적 발표 시작 — 중앙 정렬 타이틀, 위쪽 eyebrow, 아래 메타",
    inputSignature: "title + optional kicker + optional date",
    visualSketch: "[      EYEBROW      ]\n\n[    HERO TITLE    ]\n[     subtitle     ]\n\n[ author · date ]",
    tokenHints: ["typography.hero", "colors.text", "spacing.slideMarginY"],
    compatibleLayouts: ["cover"],
  },
  {
    id: "sk-cover-asym-left",
    category: "skeleton",
    name: "Asymmetric Left Cover",
    purpose: "타이틀 좌측 상단 정렬, 우측은 의도적 여백 또는 그래픽",
    inputSignature: "title + subtitle, brand-led tone",
    visualSketch: "[HERO TITLE       ]\n[that wraps tightly]\n[ subtitle        ]\n                    ◆\n[author · date]",
    tokenHints: ["typography.hero", "decorations.signatureElements"],
    compatibleLayouts: ["cover"],
  },
  {
    id: "sk-cover-split-image",
    category: "skeleton",
    name: "Split Cover (Text | Image)",
    purpose: "좌측 텍스트, 우측 풀블리드 이미지/그래픽 슬롯",
    inputSignature: "title + visual subject (product/photo)",
    visualSketch: "[ TITLE       ║         ]\n[ subtitle    ║  visual ]\n[ author      ║         ]",
    tokenHints: ["spacing.sectionGap", "colors.surfaceAlt"],
    compatibleLayouts: ["cover", "image-caption"],
  },
  {
    id: "sk-cover-dark-bold",
    category: "skeleton",
    name: "Dark Bold Cover",
    purpose: "검정 배경 + 큰 흰 타이틀. brand-bold 브랜드용 인트로",
    inputSignature: "title + 1줄 단언",
    visualSketch: "███████████████████\n█  BIG STATEMENT  █\n█   (white text)  █\n███████████████████",
    tokenHints: ["decorations.darkCover", "colors.background", "colors.textInverse"],
    compatibleLayouts: ["cover"],
  },

  // ── Section divider variants ─────────────────────────────
  {
    id: "sk-section-numbered",
    category: "skeleton",
    name: "Numbered Section Divider",
    purpose: "큰 챕터 번호(01·02) + 챕터명. 책의 챕터 펼침 같은 호흡",
    inputSignature: "chapter number + chapter title",
    visualSketch: "                  \n   01            \n   Chapter Title  \n   subtitle       \n                  ",
    tokenHints: ["typography.display", "colors.textMuted"],
    compatibleLayouts: ["section-divider"],
  },
  {
    id: "sk-section-minimal-line",
    category: "skeleton",
    name: "Minimal Line Divider",
    purpose: "한 줄 텍스트 + hairline rule만. 여백이 곧 메시지",
    inputSignature: "section title only",
    visualSketch: "                       \n                       \n  Part Two ─────────  \n  The Inflection      \n                       ",
    tokenHints: ["typography.heading", "colors.hairline"],
    compatibleLayouts: ["section-divider"],
  },
  {
    id: "sk-section-full-brand",
    category: "skeleton",
    name: "Full Brand Color Section",
    purpose: "브랜드 컬러 전면 + 흰 타이틀. 강한 챕터 전환",
    inputSignature: "chapter title + 1줄 thesis",
    visualSketch: "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\n▓                  ▓\n▓   PART THREE     ▓\n▓   thesis line    ▓\n▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓",
    tokenHints: ["colors.brandPrimary", "colors.textInverse"],
    compatibleLayouts: ["section-divider"],
  },

  // ── Title + body variants ────────────────────────────────
  {
    id: "sk-title-body-classic",
    category: "skeleton",
    name: "Classic Title + Body",
    purpose: "헤더(eyebrow+title+subtitle) 위, 단락 본문 아래. 가장 범용",
    inputSignature: "title + 1~2 paragraph body",
    visualSketch: "EYEBROW\nSlide Title\nsubtitle\n\nBody paragraph text\nthat wraps several\nlines below.",
    tokenHints: ["typography.heading", "typography.body"],
    compatibleLayouts: ["title-body"],
  },
  {
    id: "sk-title-body-pull-quote",
    category: "skeleton",
    name: "Title + Pull-quote",
    purpose: "본문 중 한 줄을 큰 강조로 띄움 — 신문 기사 스타일",
    inputSignature: "title + body + key sentence to amplify",
    visualSketch: "Title\n\nbody body body\n┌─────────────────┐\n│ KEY SENTENCE.  │\n└─────────────────┘\nmore body...",
    tokenHints: ["typography.subheading", "colors.brandPrimary"],
    compatibleLayouts: ["title-body"],
  },
  {
    id: "sk-title-body-two-block",
    category: "skeleton",
    name: "Title + Two Body Blocks",
    purpose: "단락 두 개를 위/아래로 분리, 사이에 hairline",
    inputSignature: "title + 2 distinct paragraphs",
    visualSketch: "Title\nblock 1 paragraph...\n─────────────────\nblock 2 paragraph...",
    tokenHints: ["colors.hairline"],
    compatibleLayouts: ["title-body"],
  },

  // ── Title + bullets variants ─────────────────────────────
  {
    id: "sk-bullets-numbered-grid",
    category: "skeleton",
    name: "Numbered Bullets Grid",
    purpose: "큰 번호(01·02·03) + 한 줄 핵심. 2x2 또는 1x3 그리드",
    inputSignature: "title + 3~4 short labeled items",
    visualSketch: "Title\n┌────┐ ┌────┐\n│ 01 │ │ 02 │\n│ ✓  │ │ ✓  │\n└────┘ └────┘",
    tokenHints: ["typography.subheading", "borderRadius.md"],
    compatibleLayouts: ["title-bullets"],
  },
  {
    id: "sk-bullets-icon-list",
    category: "skeleton",
    name: "Icon Bullet List",
    purpose: "각 항목 앞에 작은 아이콘/dot + 본문",
    inputSignature: "title + 3~5 items with short text",
    visualSketch: "Title\n● item one\n● item two\n● item three",
    tokenHints: ["colors.brandPrimary"],
    compatibleLayouts: ["title-bullets"],
  },
  {
    id: "sk-bullets-card-grid",
    category: "skeleton",
    name: "Card Grid Bullets",
    purpose: "각 bullet을 작은 카드로 (제목 + 1줄 설명). 3장 가로",
    inputSignature: "title + 3 items each with label + subtext",
    visualSketch: "Title\n┌───┐ ┌───┐ ┌───┐\n│ A │ │ B │ │ C │\n│txt│ │txt│ │txt│\n└───┘ └───┘ └───┘",
    tokenHints: ["borderRadius.md", "colors.surface"],
    compatibleLayouts: ["title-bullets"],
  },
  {
    id: "sk-bullets-checklist-bold",
    category: "skeleton",
    name: "Bold Checklist",
    purpose: "✓ 마크 + 굵은 핵심 단어 + 가는 부연",
    inputSignature: "title + 3~5 affirmations",
    visualSketch: "Title\n✓ Bold thing — context\n✓ Bold thing — context\n✓ Bold thing — context",
    tokenHints: ["typography.body", "colors.brandPrimary"],
    compatibleLayouts: ["title-bullets"],
  },

  // ── Two-column compare variants ──────────────────────────
  {
    id: "sk-compare-before-after",
    category: "skeleton",
    name: "Before / After Split",
    purpose: "좌(회색 톤·Before) / 우(브랜드 톤·After) 명확한 전후 대비",
    inputSignature: "compareType + left items + right items",
    visualSketch: "  BEFORE  ║  AFTER\n  · a    ║  · α\n  · b    ║  · β\n  · c    ║  · γ",
    tokenHints: ["colors.textMuted", "colors.brandPrimary"],
    compatibleLayouts: ["two-column-compare"],
  },
  {
    id: "sk-compare-vs-headed",
    category: "skeleton",
    name: "Versus Header Compare",
    purpose: "상단에 큰 VS, 좌우 칼럼은 동등 weight",
    inputSignature: "two equivalent options to weigh",
    visualSketch: "        VS\nOption A  │  Option B\n· pro     │  · pro\n· con     │  · con",
    tokenHints: ["typography.display", "colors.hairline"],
    compatibleLayouts: ["two-column-compare"],
  },
  {
    id: "sk-compare-problem-solution",
    category: "skeleton",
    name: "Problem / Solution",
    purpose: "좌측 검정 박스(문제) → 우측 흰 카드(해결). 인과 강조",
    inputSignature: "problem statement + solution statement",
    visualSketch: "┌────────┐ ┌────────┐\n│ PROBLEM│→│SOLUTION│\n│ dark   │ │ light  │\n└────────┘ └────────┘",
    tokenHints: ["colors.background", "colors.brandPrimary"],
    compatibleLayouts: ["two-column-compare"],
  },

  // ── Big stat variants ────────────────────────────────────
  {
    id: "sk-stat-mono-jumbo",
    category: "skeleton",
    name: "Mono Jumbo Stat",
    purpose: "화면 절반 차지하는 단일 숫자, 아래 작은 캡션",
    inputSignature: "single number + 1줄 caption",
    visualSketch: "EYEBROW\n\n     172%\n\n  growth caption",
    tokenHints: ["typography.stat", "colors.brandPrimary"],
    compatibleLayouts: ["big-stat"],
  },
  {
    id: "sk-stat-trio",
    category: "skeleton",
    name: "Stat Trio Row",
    purpose: "통계 3개 가로 나열, 각각 큰 숫자 + 라벨",
    inputSignature: "3 stats with number + label each",
    visualSketch: "  87%  │  $4.2B  │  3.4×\n users │ market  │ growth",
    tokenHints: ["typography.stat", "colors.hairline"],
    compatibleLayouts: ["big-stat", "title-bullets"],
  },
  {
    id: "sk-stat-with-context",
    category: "skeleton",
    name: "Stat with Context Sentence",
    purpose: "큰 숫자 + 옆에 긴 설명 문장",
    inputSignature: "stat + multi-line context paragraph",
    visualSketch: "       │ Long context that\n  87%  │ explains why this\n       │ number matters.\n  users│",
    tokenHints: ["typography.stat", "typography.body"],
    compatibleLayouts: ["big-stat"],
  },

  // ── Quote variants ───────────────────────────────────────
  {
    id: "sk-quote-pull-full",
    category: "skeleton",
    name: "Full Pull Quote",
    purpose: "큰 인용 마크 + 한 문장. 작가/직책 작게",
    inputSignature: "1 quote sentence + attribution",
    visualSketch: '"\n"The single most\n  important thing."\n\n— Name, Role',
    tokenHints: ["typography.display"],
    compatibleLayouts: ["quote"],
  },
  {
    id: "sk-quote-portrait-left",
    category: "skeleton",
    name: "Portrait + Quote",
    purpose: "좌측 원형 인물 자리, 우측 인용",
    inputSignature: "quote + person name + role + portrait slot",
    visualSketch: "  ◯  │ \"Quote that\n      │  carries weight.\"\n      │ — Name, Role",
    tokenHints: ["borderRadius.pill", "typography.subheading"],
    compatibleLayouts: ["quote"],
  },
  {
    id: "sk-quote-multi-stack",
    category: "skeleton",
    name: "Stacked Multi-quotes",
    purpose: "여러 인용을 위/아래 스택, 다중 증언",
    inputSignature: "2~3 short quotes + attributions",
    visualSketch: "\"Q1 here\" — A\n────────────\n\"Q2 here\" — B\n────────────\n\"Q3 here\" — C",
    tokenHints: ["colors.hairline"],
    compatibleLayouts: ["quote"],
  },

  // ── Timeline variants ────────────────────────────────────
  {
    id: "sk-timeline-horizontal-dots",
    category: "skeleton",
    name: "Horizontal Dot Timeline",
    purpose: "수평선 + 단계별 dot + 라벨. 가장 표준",
    inputSignature: "3~5 sequential steps with label",
    visualSketch: "● ─── ● ─── ● ─── ●\n2020  2022  2024  2026",
    tokenHints: ["colors.hairline-soft", "colors.brandPrimary"],
    compatibleLayouts: ["timeline"],
  },
  {
    id: "sk-timeline-stepped-vertical",
    category: "skeleton",
    name: "Vertical Step Timeline",
    purpose: "위→아래 흐름 단계, 각 단계에 설명 박스",
    inputSignature: "3~5 phases with description",
    visualSketch: "● Step 1\n│  description\n● Step 2\n│  description\n● Step 3",
    tokenHints: ["colors.hairline"],
    compatibleLayouts: ["timeline"],
  },
  {
    id: "sk-timeline-highlight-current",
    category: "skeleton",
    name: "Timeline with Current Highlight",
    purpose: "타임라인 중 1개 단계를 brand color로 강조 (현재 위치)",
    inputSignature: "steps + index of 'current'",
    visualSketch: "● ─── ● ─── ◉ ─── ●\n           NOW",
    tokenHints: ["colors.brandPrimary"],
    compatibleLayouts: ["timeline"],
  },

  // ── Image / visual variants ──────────────────────────────
  {
    id: "sk-image-full-overlay",
    category: "skeleton",
    name: "Full-bleed Image + Overlay Text",
    purpose: "이미지가 슬라이드 전체, 좌하단에 텍스트 오버레이",
    inputSignature: "image + 1 sentence headline",
    visualSketch: "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\n▓                 ▓\n▓                 ▓\n▓ Headline text   ▓\n▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓",
    tokenHints: ["colors.textInverse"],
    compatibleLayouts: ["image-caption"],
  },
  {
    id: "sk-image-caption-side",
    category: "skeleton",
    name: "Image + Side Caption",
    purpose: "이미지 70% + 옆 30% 설명. product/portfolio 카드",
    inputSignature: "image + caption + optional title",
    visualSketch: "[ image area ] │ Caption\n[            ] │ goes here\n[            ] │ in two\n[            ] │ lines.",
    tokenHints: ["typography.body"],
    compatibleLayouts: ["image-caption"],
  },
  {
    id: "sk-image-gallery-3",
    category: "skeleton",
    name: "3-up Image Gallery",
    purpose: "이미지 3개 가로 + 아래 공통 캡션",
    inputSignature: "3 images + 1 group caption",
    visualSketch: "[img]  [img]  [img]\n      caption",
    tokenHints: ["spacing.itemGap"],
    compatibleLayouts: ["image-caption"],
  },

  // ── Closing variants ─────────────────────────────────────
  {
    id: "sk-closing-cta-bold",
    category: "skeleton",
    name: "Bold CTA Closing",
    purpose: "큰 headline + 1줄 부연 + brand-color CTA 버튼",
    inputSignature: "headline + subheadline + CTA label",
    visualSketch: "  Thank You\n  Let's build it.\n\n  [ Start now → ]",
    tokenHints: ["colors.brandPrimary", "borderRadius.pill"],
    compatibleLayouts: ["closing"],
  },
  {
    id: "sk-closing-contact",
    category: "skeleton",
    name: "Contact Info Closing",
    purpose: "이메일·URL·소셜 등 contact info 그리드",
    inputSignature: "headline + 2~4 contact lines",
    visualSketch: "  Thanks.\n  hi@team.com\n  team.com\n  @team",
    tokenHints: ["typography.body", "colors.textMuted"],
    compatibleLayouts: ["closing"],
  },
  {
    id: "sk-closing-quote-end",
    category: "skeleton",
    name: "Quote Closing",
    purpose: "마지막 슬라이드를 인용으로 — 여운 남김",
    inputSignature: "final quote + author",
    visualSketch: "                 \n  \"Final thought\"\n  — Author       \n                 ",
    tokenHints: ["typography.display"],
    compatibleLayouts: ["closing", "quote"],
  },

  // ── Hybrid / specialty ───────────────────────────────────
  {
    id: "sk-hero-stat-strip",
    category: "skeleton",
    name: "Hero + Bottom Stat Strip",
    purpose: "상단 큰 헤드라인 + 하단에 3개 stat 미니 strip",
    inputSignature: "headline + 3 supporting numbers",
    visualSketch: "[ HEADLINE        ]\n[ that anchors   ]\n────────────────\n 87%  │ 4.2B │ 3.4×",
    tokenHints: ["typography.heading", "typography.caption"],
    compatibleLayouts: ["title-body", "big-stat"],
  },
  {
    id: "sk-dark-insight-panel",
    category: "skeleton",
    name: "Dark Insight Panel",
    purpose: "슬라이드 우측에 검정 박스(흰 텍스트)로 핵심 메시지 분리",
    inputSignature: "context body + 1 insight to highlight",
    visualSketch: "Context        █INSIGHT█\nblock here     █white █\n               █text  █",
    tokenHints: ["colors.background", "colors.textInverse", "borderRadius.md"],
    compatibleLayouts: ["title-body", "two-column-compare"],
  },
  {
    id: "sk-logo-grid",
    category: "skeleton",
    name: "Logo / Partner Grid",
    purpose: "고객/파트너 로고 4×3 또는 5×2 그리드",
    inputSignature: "headline + 8~12 logo slots",
    visualSketch: "Trusted by:\n[L][L][L][L][L]\n[L][L][L][L][L]",
    tokenHints: ["spacing.itemGap", "colors.hairline"],
    compatibleLayouts: ["title-bullets"],
  },
  {
    id: "sk-three-col-feature",
    category: "skeleton",
    name: "Three-column Feature",
    purpose: "3개 feature 칼럼 — 아이콘 + 제목 + 설명",
    inputSignature: "3 features each with icon hint + title + 2 lines",
    visualSketch: "◆ Title    ◆ Title    ◆ Title\n  desc 1     desc 2     desc 3\n  line 2     line 2     line 2",
    tokenHints: ["typography.subheading"],
    compatibleLayouts: ["title-bullets"],
  },
  {
    id: "sk-zigzag-narrative",
    category: "skeleton",
    name: "Zigzag Narrative",
    purpose: "여러 슬라이드 시퀀스: 좌-우-좌 교차로 흐름 만들기",
    inputSignature: "title + alternating side (left|right)",
    visualSketch: "TITLE              \nbody on left │ ────\n────         │ body\n             │ right",
    tokenHints: ["spacing.sectionGap"],
    compatibleLayouts: ["title-body", "image-caption"],
  },
];
